name: renovate
on:
  # schedule:
  #   - cron: "0 8 * * MON"
  push:
    branches:
      - renovate
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade the Npm library
        run: |
          echo 'Upgrade the Npm library'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          echo ' export PATH=~/.npm-global/bin:$PATH' >> ~/.bash_profile
          source ~/.bash_profile
          npm install -g yarn
          npx renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          RENOVATE_CONFIG_FILE: .github/renovate-config.js
